name: nestbox-workflow
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip=24.2
  - pip:
      - matplotlib==3.9.2
      - pandas==2.2.2
      - numpy==1.26.4
      - astral==3.2
      - pytz==2024.1
      - nbformat==5.10.4
